### ISSUE TITLE
Monitor EC2

### ISSUE THREAD

**Issue by jmcarp** [18F/cf-limit-check#12]
We aren't currently using awslimitchecker to monitor EC2 limits, since there were a few govcloud-related issues upstream that caused this check to crash. Those issues were fixed in https://github.com/jantman/awslimitchecker/pull/251; once upstream cuts a release, we should bump the version here and add the EC2 service to our concourse configuration.

**Comment by jantman** [comment]
Apologies for the delays. PR is merged and released in 0.8.0, which is now live on PyPI. Note that there are a few additional permissions required in this release and a breaking API change; please see [the 0.8.0 changelog](http://awslimitchecker.readthedocs.io/en/0.8.0/changes.html#id1) for further information.

Thank you SO much again, @jmcarp , for your contributions to this release.
